/**
 * Exhaustive consumer contract for erased public names in the built packages.
 *
 * The three dist-type tsconfigs compile this file against ESM declarations,
 * CJS declarations, and TypeScript 4.9. Keep every type explicit so a missing
 * declaration export fails independently of runtime bundle tests.
 */
export type {
  ExtraOptions,
  Logger,
  QwpArrayValue,
  QwpBinaryConnection,
  QwpBindSetter,
  QwpBindType,
  QwpCacheResetMessage,
  QwpClientFactories,
  QwpClientMetrics,
  QwpClientPoolOptions,
  QwpColumnBuffer,
  QwpColumnType,
  QwpConnectionCloseInfo,
  QwpConnectionFactory,
  QwpDecimalInput,
  QwpDecimalValue,
  QwpDoubleArrayInput,
  QwpEgressCompression,
  QwpEgressMessage,
  QwpEgressMetrics,
  QwpEgressQueryOptions,
  QwpEgressReplayResetEvent,
  QwpEgressRoutingOptions,
  QwpEgressSessionOptions,
  QwpEgressTransportMetrics,
  QwpEgressViewCallbackControl,
  QwpEgressViewQuery,
  QwpEncodedBinds,
  QwpExecDoneMessage,
  QwpExtraOptions,
  QwpFailoverAttempt,
  QwpFrame,
  QwpFrameHeader,
  QwpGeohashInput,
  QwpGeohashValue,
  QwpHandshakeMetadata,
  QwpIngressEncodeOptions,
  QwpIngressErrorEvent,
  QwpIngressMetrics,
  QwpIngressProgressEvent,
  QwpIngressProgressKind,
  QwpIngressReplayRecord,
  QwpIngressReplayReference,
  QwpIngressReplayStore,
  QwpIngressResponse,
  QwpIngressSendResult,
  QwpIngressServerInfo,
  QwpIngressSessionOptions,
  QwpIngressSymbolDictionaryDelta,
  QwpIngressTableResult,
  QwpIngressTransportMetrics,
  QwpInitialConnectMode,
  QwpInt64,
  QwpIpv4Input,
  QwpLong256Input,
  QwpLong256Value,
  QwpLong256Words,
  QwpLongArrayInput,
  QwpNegotiatedEgressCompression,
  QwpNestedLongArray,
  QwpNestedNumberArray,
  QwpNodeClientConfigOptions,
  QwpNodeClientOptions,
  QwpNodeEgressOptions,
  QwpNodeFileReplayStoreMetrics,
  QwpNodeFileReplayStoreOptions,
  QwpNodeIngressOptions,
  QwpNodeOrphanDrainEvent,
  QwpNodeOrphanDrainEventKind,
  QwpNodeOrphanDrainSession,
  QwpNodeOrphanDrainerMetrics,
  QwpNodeOrphanDrainerOptions,
  QwpNodeReplayDataLossReport,
  QwpNodeReplayRecoveryEvent,
  QwpNodeStoreAndForwardOptions,
  QwpNodeUdpMetrics,
  QwpNodeUdpOptions,
  QwpNodeUdpSocketLike,
  QwpNodeUpgradeRejection,
  QwpNodeWebSocketOptions,
  QwpPoolSlotReservation,
  QwpQueryCompletion,
  QwpQueryErrorMessage,
  QwpQueryRequest,
  QwpReconnectEvent,
  QwpReconnectEventKind,
  QwpReconnectOptions,
  QwpResourcePoolMetrics,
  QwpResultArrayValue,
  QwpResultBatchMessage,
  QwpResultBatchViewHandler,
  QwpResultColumn,
  QwpResultColumnSchema,
  QwpResultEndMessage,
  QwpResultRowViewCallback,
  QwpResultValue,
  QwpSenderEncodeOptions,
  QwpSenderError,
  QwpSenderErrorCategory,
  QwpSenderErrorPolicy,
  QwpSenderErrorResponseContext,
  QwpSenderLogger,
  QwpSenderMetrics,
  QwpSenderOptions,
  QwpSenderSession,
  QwpSenderSessionFactory,
  QwpServerInfoMessage,
  QwpSfBackpressurePolicy,
  QwpSfDurability,
  QwpSymbolValue,
  QwpTarget,
  QwpTimestampUnit,
  QwpUpgradeErrorDetails,
  QwpUpgradeErrorKind,
  QwpUpgradeTimeoutPhase,
  QwpUuidInput,
  QwpUuidValue,
  QwpWebSocketConnectOptions,
  QwpWebSocketLike,
  QwpWriterColumn,
  QwpWriterColumnKind,
  QwpWriterRow,
  QwpWriterSchema,
  SenderBuffer,
  SenderTransport,
  TimestampUnit,
} from "@questdb/nodejs-client";

// Resolve the shared contract independently through the browser package.
export type {
  QwpArrayValue as BrowserQwpArrayValue,
  QwpBinaryConnection as BrowserQwpBinaryConnection,
  QwpBindSetter as BrowserQwpBindSetter,
  QwpBindType as BrowserQwpBindType,
  QwpBrowserClientEgressOptions,
  QwpBrowserClientIngressOptions,
  QwpBrowserClientOptions,
  QwpBrowserClusterOptions,
  QwpBrowserEgressOptions,
  QwpBrowserFetch,
  QwpBrowserSessionAuthentication,
  QwpBrowserSessionBootstrapConfig,
  QwpBrowserSessionBootstrapOptions,
  QwpBrowserSessionBootstrapResult,
  QwpBrowserSplitClientOptions,
  QwpBrowserUnifiedClientOptions,
  QwpBrowserWebSocketOptions,
  QwpCacheResetMessage as BrowserQwpCacheResetMessage,
  QwpClientFactories as BrowserQwpClientFactories,
  QwpClientMetrics as BrowserQwpClientMetrics,
  QwpClientPoolOptions as BrowserQwpClientPoolOptions,
  QwpColumnBuffer as BrowserQwpColumnBuffer,
  QwpColumnType as BrowserQwpColumnType,
  QwpConnectionCloseInfo as BrowserQwpConnectionCloseInfo,
  QwpConnectionFactory as BrowserQwpConnectionFactory,
  QwpDecimalInput as BrowserQwpDecimalInput,
  QwpDecimalValue as BrowserQwpDecimalValue,
  QwpDoubleArrayInput as BrowserQwpDoubleArrayInput,
  QwpEgressCompression as BrowserQwpEgressCompression,
  QwpEgressMessage as BrowserQwpEgressMessage,
  QwpEgressMetrics as BrowserQwpEgressMetrics,
  QwpEgressQueryOptions as BrowserQwpEgressQueryOptions,
  QwpEgressReplayResetEvent as BrowserQwpEgressReplayResetEvent,
  QwpEgressRoutingOptions as BrowserQwpEgressRoutingOptions,
  QwpEgressSessionOptions as BrowserQwpEgressSessionOptions,
  QwpEgressTransportMetrics as BrowserQwpEgressTransportMetrics,
  QwpEgressViewCallbackControl as BrowserQwpEgressViewCallbackControl,
  QwpEgressViewQuery as BrowserQwpEgressViewQuery,
  QwpEncodedBinds as BrowserQwpEncodedBinds,
  QwpExecDoneMessage as BrowserQwpExecDoneMessage,
  QwpFailoverAttempt as BrowserQwpFailoverAttempt,
  QwpFrame as BrowserQwpFrame,
  QwpFrameHeader as BrowserQwpFrameHeader,
  QwpGeohashInput as BrowserQwpGeohashInput,
  QwpGeohashValue as BrowserQwpGeohashValue,
  QwpHandshakeMetadata as BrowserQwpHandshakeMetadata,
  QwpIngressEncodeOptions as BrowserQwpIngressEncodeOptions,
  QwpIngressErrorEvent as BrowserQwpIngressErrorEvent,
  QwpIngressMetrics as BrowserQwpIngressMetrics,
  QwpIngressProgressEvent as BrowserQwpIngressProgressEvent,
  QwpIngressProgressKind as BrowserQwpIngressProgressKind,
  QwpIngressReplayRecord as BrowserQwpIngressReplayRecord,
  QwpIngressReplayReference as BrowserQwpIngressReplayReference,
  QwpIngressReplayStore as BrowserQwpIngressReplayStore,
  QwpIngressResponse as BrowserQwpIngressResponse,
  QwpIngressSendResult as BrowserQwpIngressSendResult,
  QwpIngressServerInfo as BrowserQwpIngressServerInfo,
  QwpIngressSessionOptions as BrowserQwpIngressSessionOptions,
  QwpIngressSymbolDictionaryDelta as BrowserQwpIngressSymbolDictionaryDelta,
  QwpIngressTableResult as BrowserQwpIngressTableResult,
  QwpIngressTransportMetrics as BrowserQwpIngressTransportMetrics,
  QwpInitialConnectMode as BrowserQwpInitialConnectMode,
  QwpInt64 as BrowserQwpInt64,
  QwpIpv4Input as BrowserQwpIpv4Input,
  QwpLong256Input as BrowserQwpLong256Input,
  QwpLong256Value as BrowserQwpLong256Value,
  QwpLong256Words as BrowserQwpLong256Words,
  QwpLongArrayInput as BrowserQwpLongArrayInput,
  QwpNegotiatedEgressCompression as BrowserQwpNegotiatedEgressCompression,
  QwpNestedLongArray as BrowserQwpNestedLongArray,
  QwpNestedNumberArray as BrowserQwpNestedNumberArray,
  QwpPoolSlotReservation as BrowserQwpPoolSlotReservation,
  QwpQueryCompletion as BrowserQwpQueryCompletion,
  QwpQueryErrorMessage as BrowserQwpQueryErrorMessage,
  QwpQueryRequest as BrowserQwpQueryRequest,
  QwpReconnectEvent as BrowserQwpReconnectEvent,
  QwpReconnectEventKind as BrowserQwpReconnectEventKind,
  QwpReconnectOptions as BrowserQwpReconnectOptions,
  QwpResourcePoolMetrics as BrowserQwpResourcePoolMetrics,
  QwpResultArrayValue as BrowserQwpResultArrayValue,
  QwpResultBatchMessage as BrowserQwpResultBatchMessage,
  QwpResultBatchViewHandler as BrowserQwpResultBatchViewHandler,
  QwpResultColumn as BrowserQwpResultColumn,
  QwpResultColumnSchema as BrowserQwpResultColumnSchema,
  QwpResultEndMessage as BrowserQwpResultEndMessage,
  QwpResultRowViewCallback as BrowserQwpResultRowViewCallback,
  QwpResultValue as BrowserQwpResultValue,
  QwpSenderEncodeOptions as BrowserQwpSenderEncodeOptions,
  QwpSenderError as BrowserQwpSenderError,
  QwpSenderErrorCategory as BrowserQwpSenderErrorCategory,
  QwpSenderErrorPolicy as BrowserQwpSenderErrorPolicy,
  QwpSenderErrorResponseContext as BrowserQwpSenderErrorResponseContext,
  QwpSenderLogger as BrowserQwpSenderLogger,
  QwpSenderMetrics as BrowserQwpSenderMetrics,
  QwpSenderOptions as BrowserQwpSenderOptions,
  QwpSenderSession as BrowserQwpSenderSession,
  QwpSenderSessionFactory as BrowserQwpSenderSessionFactory,
  QwpServerInfoMessage as BrowserQwpServerInfoMessage,
  QwpSymbolValue as BrowserQwpSymbolValue,
  QwpTarget as BrowserQwpTarget,
  QwpTimestampUnit as BrowserQwpTimestampUnit,
  QwpUpgradeErrorDetails as BrowserQwpUpgradeErrorDetails,
  QwpUpgradeErrorKind as BrowserQwpUpgradeErrorKind,
  QwpUpgradeTimeoutPhase as BrowserQwpUpgradeTimeoutPhase,
  QwpUuidInput as BrowserQwpUuidInput,
  QwpUuidValue as BrowserQwpUuidValue,
  QwpWebSocketConnectOptions as BrowserQwpWebSocketConnectOptions,
  QwpWebSocketLike as BrowserQwpWebSocketLike,
  QwpWriterColumn as BrowserQwpWriterColumn,
  QwpWriterColumnKind as BrowserQwpWriterColumnKind,
  QwpWriterRow as BrowserQwpWriterRow,
  QwpWriterSchema as BrowserQwpWriterSchema,
} from "@questdb/browser-client";
