name: build

on:
  push:

jobs:
  build:
    name: Build @questdb/nodejs-questdb-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linter
        run: npm run eslint

      - name: Publish @questdb/nodejs-questdb-client to npm
        if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          access: public
          check-version: true
          package: package.json
